- name: Setup 
  hosts: all
  become: yes 
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Wait to become available
      shell: cloud-init status --wait
      args: 
        executable: /bin/bash

    - name: install ca-certificates
      apt:
        name: ca-certificates
        state: present

    - name: Pendejo aka MitMA problem
      replace:
        path: /etc/apt/sources.list
        regexp: 'http://ports.ubuntu.com'
        replace: 'https://ports.ubuntu.com'

    - name: Update 
      apt: 
        update_cache: yes 

    - name: Disable swap if enabled
      shell: |
        if swapon --summary | grep -q '^'; then
          swapoff -a
        fi

    - name: Permanently disable swap
      replace: 
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - curl
          - gnupg
          - lsb-release
          - nmap
          - nfs-common
          - openssh-server
          - open-iscsi
        state: present

    - name: Enable and start isci
      systemd:
        name: iscsid
        state: started
        enabled: yes

    - name: Install ContainerD
      apt:
        name: containerd
        state: present 

    - name: Create ContainerD config
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml 
        sed -i "s/SystemdCgroup = false/SystemdCgroup = true/g" /etc/containerd/config.toml 
      notify: Restart ContainerD

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Br_netfilter load on boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter

    - name: Set sysctl params for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
      notify: Reload sysctl

    - name: Apply sysctl params
      command: sysctl --system

    - name: Force Google DNS
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        insertbefore: BOF

    - name: Make keyrings directory 
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes GPG key 
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /'

    - name: Update apt cache after adding Kubernetes repo
      apt:
        update_cache: yes

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubeadm
          - kubelet 
          - kubectl
        state: present

    - name: Pre pull images for kubeadm init
      command: kubeadm config images pull
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Cluster initialization with kubeadm
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.10
      args:
        creates: /etc/kubernetes/admin.conf
      run_once: true

    - name: Hold kubeadm, kubelet, kubectl at current version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: [kubeadm, kubelet, kubectl]

    - name: Create .kube directory for root
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to root kubeconfig
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: Create .kube directory for vagrant
      ansible.builtin.file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy admin.conf to vagrant kubeconfig
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'


    - name: Remove control-plane taint so pods can schedule on single node
      shell: |
        kubectl taint nodes --all node-role.kubernetes.io/control-plane- || true 

    - name: Install Calico CNI
      shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
        kubectl set env daemonset/calico-node -n kube-system \
          IP_AUTODETECTION_METHOD=interface=eth1 \
          CALICO_IPV4POOL_CIDR=10.244.0.0/16 || true
      run_once: true

    - name: Wait for all nodes to be ready
      shell: |
        kubectl wait --for=condition=Ready nodes --all --timeout=300s
      ignore_errors: yes

    - name: Install Longhorn 
      shell: |
        kubectl create namespace longhorn-system --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.11.1/deploy/longhorn.yaml
      run_once: true


    - name: Wait for Longhorn to be ready
      shell: |
        kubectl wait --for=condition=Ready pod -l app=longhorn-manager \
          -n longhorn-system --timeout=300s
      run_once: true

    - name: Set Longhorn default replicas to 1
      shell: |
        kubectl patch storageclass longhorn -p '{"parameters":{"numberOfReplicas":"1"}}'

    - name: Expose Longhorn UI
      shell: |
        kubectl patch svc longhorn-frontend -n longhorn-system \
          -p '{"spec": {"type": "NodePort", "ports": [{"port": 8000, "targetPort": 8000, "nodePort": 30080}]}}'
      run_once: true

    - name: Write manifest for postgres for Longhorn
      copy:
        dest: /home/vagrant/postgres-deployment.yaml
        content: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: postgres-pvc
            namespace: default
            labels:
              recurring-job-group.longhorn.io/default: enabled
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: longhorn

          ---
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: postgres-deployment
          spec:
            serviceName: "postgres"
            replicas: 1
            selector:
              matchLabels:
                app: postgres
            template:
              metadata:
                labels:
                  app: postgres
              spec:
                containers:
                  - name: postgres
                    image: postgres:16
                    env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "Kakashi19096"
                      - name: PGDATA
                        value: "/var/lib/postgresql/data/pgdata"
                    ports:
                      - containerPort: 5432
                    volumeMounts:
                      - name: pgdata
                        mountPath: /var/lib/postgresql/data
                        subPath: pgdata
                volumes:
                  - name: pgdata
                    persistentVolumeClaim:
                      claimName: postgres-pvc

            volumeClaimTemplates:
              - metadata:
                  name: pgdata
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  resources:
                    requests:
                      storage: 2Gi
                  storageClassName: longhorn

          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: postgres-service
          spec:
            clusterIP: None
            selector:
              app: postgres
            ports:
              - protocol: TCP
                port: 5432
                targetPort: 5432
    


    - name: Deploy PostgreSQL on Kubernetes
      shell: |
        kubectl apply -f /home/vagrant/postgres-deployment.yaml
      run_once: true

    - name: Write something in DB for testing
      shell: |
        kubectl wait --for=condition=Ready pod -l app=postgres --timeout=300s
        POD=$(kubectl get pod -l app=postgres -o jsonpath='{.items[0].metadata.name}')
        kubectl exec $POD -- psql -U postgres -c \
          "CREATE TABLE IF NOT EXISTS test_table (id SERIAL PRIMARY KEY, name VARCHAR(255));"
        kubectl exec $POD -- psql -U postgres -c \
          "INSERT INTO test_table (name) VALUES ('testdata'), ('moredata');"
      run_once: true
      retries: 5
      delay: 30
      register: db_setup_result
      until: db_setup_result.rc == 0

    - name: Write Longhorn RecurringJob manifest
      copy:
        dest: /home/vagrant/longhorn-cron.yaml
        content: |
          apiVersion: longhorn.io/v1beta2
          kind: RecurringJob
          metadata:
            name: postgres-snapshot-cron
            namespace: longhorn-system
          spec:
            cron: "*/5 * * * *"
            task: "snapshot"
            groups:
              - default
            retain: 3
            concurrency: 1

    - name: Deploy Longhorn 5-minute cron
      shell: kubectl apply -f /home/vagrant/longhorn-cron.yaml
      run_once: true

    - name: Install Snapshot Controller and CRDs
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
        sleep 20
      run_once: true


    - name: Wait for VolumeSnapshot CRDs to be registered
      shell: |
        kubectl wait --for condition=established --timeout=20s crd/volumesnapshotclasses.snapshot.storage.k8s.io
        kubectl wait --for condition=established --timeout=20s crd/volumesnapshots.snapshot.storage.k8s.io
        kubectl wait --for condition=established --timeout=20s crd/volumesnapshotcontents.snapshot.storage.k8s.io
      run_once: true

    - name: Create Longhorn VolumeSnapshotClass
      copy:
        dest: /home/vagrant/longhorn-snapshot-class.yaml
        content: |
          kind: VolumeSnapshotClass
          apiVersion: snapshot.storage.k8s.io/v1
          metadata:
            name: longhorn
          driver: driver.longhorn.io
          deletionPolicy: Delete

    - name: Apply Longhorn VolumeSnapshotClass
      shell: kubectl apply -f /home/vagrant/longhorn-snapshot-class.yaml
      run_once: true

    - name: Write manual VolumeSnapshot for restore testing
      copy:
        dest: /home/vagrant/manual-snapshot.yaml
        content: |
          apiVersion: snapshot.storage.k8s.io/v1
          kind: VolumeSnapshot
          metadata:
            name: postgres-restore-point
          spec:
            volumeSnapshotClassName: longhorn
            source:
              persistentVolumeClaimName: postgres-pvc

    - name: Write Restore PVC manifest
      copy:
        dest: /home/vagrant/restore-postgres.yaml
        content: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: postgres-restore-pvc
            namespace: default
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: longhorn
            dataSource:
              name: postgres-restore-point
              kind: VolumeSnapshot
              apiGroup: snapshot.storage.k8s.io

  handlers:
    - name: Restart ContainerD
      service:
        name: containerd
        state: restarted

    - name: Reload sysctl
      command: sysctl --system



        

