Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end 
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.box = "bento/ubuntu-22.04"  
    config.vm.provision "ansible" do |ansible|
    ansible.playbook = "Setup.yaml"
    ansible.groups = {
    "master" => ["default"]
    }
    end
end
