apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authentik-platform-alerts.yaml
  - postgres-hourly-snapshot.yaml
  - platformcheck-crd.yaml
  - authentik-platformcheck.yaml