{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin" (include "keycloak.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.secretKeys.username }}: {{ .Values.admin.username | b64enc | quote }}
  {{ .Values.admin.secretKeys.password }}: {{ .Values.admin.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "keycloak.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.secretKeys.username }}: {{ .Values.database.username | b64enc | quote }}
  {{ .Values.database.secretKeys.password }}: {{ .Values.database.password | b64enc | quote }}
{{- end }}