{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.secretKeys.usernameKey }}: {{ .Values.admin.username | b64enc | quote }}
  {{ .Values.admin.secretKeys.passwordKey }}: {{ .Values.admin.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque  # Ensure this is NOT indented further than 'metadata'
data:
  {{ .Values.database.secretKeys.usernameKey }}: {{ .Values.database.username | b64enc | quote }}
  {{ .Values.database.secretKeys.passwordKey }}: {{ .Values.database.password | b64enc | quote }}
{{- end }}