replicaCount: 1

image:
  tag: "2025.12"

extraLabels:
  version: green

worker:
  replicaCount: 1

authentik:
  postgresql:
    host: postgres-postgresql.postgres.svc.cluster.local
    port: "5432"
    user: authentik
    password: authentik
    name: authentik_green

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 90

