replicaCount: 1

image:
  repository: ghcr.io/goauthentik/server
  tag: "2025.10.4"
  pullPolicy: IfNotPresent

authentik:
  secret:
    create: false
    existingSecret: authentik-runtime-secret
    secretKeyKey: AUTHENTIK_SECRET_KEY

  postgresql:
    host: postgres-postgresql.postgres.svc.cluster.local
    port: "5432"
    user: authentik
    name: authentik
    existingSecret: postgres-postgresql
    passwordKey: password

  bootstrap:
    enabled: false
    existingSecret: authentik-bootstrap-secret
    passwordKey: AUTHENTIK_BOOTSTRAP_PASSWORD
    emailKey: AUTHENTIK_BOOTSTRAP_EMAIL
    tokenKey: AUTHENTIK_BOOTSTRAP_TOKEN

extraLabels: {}

server:
  command: "server"

worker:
  command: "worker"
  replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 9000

ingress:
  enabled: true
  className: "haproxy"
  annotations:
    kubernetes.io/ingress.class: "haproxy"
  hosts:
    - host: authentik.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

serviceAccount:
  automount: false

media:
  enabled: true

startupProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60
  httpGet:
    path: /-/health/live/
    port: 9000

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  httpGet:
    path: /-/health/ready/
    port: 9000

livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  httpGet:
    path: /-/health/live/
    port: 9000
