apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-healthcheck
  namespace: keycloak
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9000
