replicaCount: 1

image:
  tag: "26.0.0"

extraLabels:
  version: green

admin:
  existingSecret: "keycloak-admin"

database:
  existingSecret: "keycloak-db"

nodeSelector: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70