replicaCount: 2

image:
  tag: "25.0.1"

extraLabels:
  version: blue

admin:
  existingSecret: "keycloak-admin"

database:
  existingSecret: "keycloak-db"

extraEnv:
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: "-XX:UseSVE=0"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_LOG_LEVEL
    value: "INFO"

nodeSelector:
  node-role: worker