replicaCount: 2

image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  tag: "25.0.1"

admin: 
  username: admin
  password: admin
  existingSecret: ""
  secretKeys:
    usernameKey: admin-username
    passwordKey: admin-password

database: 
  vendor: postgres
  host: "postgres-postgresql.postgres.svc.cluster.local"
  port: 5432
  name: keycloak 
  username: keycloak
  existingSecret: "keycloak-db"
  secretKeys:
    usernameKey: "username"
    passwordKey: "password"

startMode: "start"

hostname: 
  hostname: ""
  hostnameStrict: false 

service:
  type: ClusterIP
  port: 80
  httpsPort: 443
  httpContainerPort: 8080
  httpsContainerPort: 8443

ingress:
  enabled: true 
  className: "haproxy"
  annotations: 
    kubernetes.io/ingress.class: "haproxy"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: keycloak.local
      paths:
        - path: /
          pathType: Prefix

  tls: []

resources: 
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

podSecurityContext:
  fsGroup: 1000

containerSecurityContext:

  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false


extraEnv: 
  - name: JAVA_OPTS_APPEND
    value: "-XX:UseSVE=0 "
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_LOG_LEVEL
    value: "DEBUG"


livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  httpGet: 
    path: /health/live
    port: 9000

readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  httpGet:
    path: /health/ready
    port: 9000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""
  automount: false
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: []
  hostname:
    hostname: "" 
    hostnameStrict: false
  rules: []

blueGreen:
  enabled: true
  active: blue

  blue:
    image:
      tag: "25.0.1"
  green:
    image:
      tag: "26.0.0"

prometheusRule:
  enabled: true

serviceMonitor:
  enabled: true