apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-allow-scrape-egress
  namespace: monitoring
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - prometheus
          - kube-prometheus-stack-prometheus
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9100
        - protocol: TCP
          port: 9187
        - protocol: TCP
          port: 10250
        - protocol: TCP
          port: 10255
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9093
