apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alertmanager-allow-prometheus
  namespace: monitoring
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - alertmanager
          - kube-prometheus-stack-alertmanager
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - prometheus
                  - kube-prometheus-stack-prometheus
      ports:
        - protocol: TCP
          port: 9093
