Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end 
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"
  end
  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "slave"
    worker1.vm.network "private_network", ip: "192.168.56.11"
  end
  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker"
    worker2.vm.network "private_network", ip: "192.168.56.12"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
    ansible.limit = "all"
  end
end
