Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end 
  config.vm.box = "bento/ubuntu-22.04"
    config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
    ansible.limit = "all"
  end
end
