apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Odasaku-Khan/DevOpsII.git
    targetRevision: main
    path: project/helm-charts/keycloak
    helm:
      valueFiles:
        - values.yaml
        - values-green.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false