apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Odasaku-Khan/DevOpsII.git
    targetRevision: main
    path: project/helm-charts/keycloak
    helm:
      valueFiles:
        - values.yaml
        - values-blue.yaml     # overrides only image tag + version label
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true