apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quota
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Odasaku-Khan/DevOpsII
    path: project/apps/quota
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true