apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik.fullname" . }}-secret
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: {{ .Values.authentik.secretKey | quote }}
  AUTHENTIK_POSTGRESQL__PASSWORD: {{ .Values.authentik.postgresql.password | quote }}
  AUTHENTIK_BOOTSTRAP_PASSWORD: {{ .Values.authentik.bootstrap.password | quote }}
  AUTHENTIK_BOOTSTRAP_EMAIL: {{ .Values.authentik.bootstrap.email | quote }}
  AUTHENTIK_BOOTSTRAP_TOKEN: {{ .Values.authentik.bootstrap.token | quote }}