apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authentik.fullname" . }}-server
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authentik.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "authentik.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
        {{- with .Values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /media
          args:
            - {{ .Values.server.command | quote }}
          ports:
            - name: http
              containerPort: 9000
            - name: metrics
              containerPort: 9300
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: {{ .Values.authentik.postgresql.host | quote }}
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: {{ .Values.authentik.postgresql.port | quote }}
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.authentik.postgresql.name | quote }}
            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.authentik.postgresql.user | quote }}
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "authentik.postgresql.existingSecret is required" .Values.authentik.postgresql.existingSecret | quote }}
                  key: {{ .Values.authentik.postgresql.passwordKey | quote }}
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "authentik.secret.existingSecret is required" .Values.authentik.secret.existingSecret | quote }}
                  key: {{ .Values.authentik.secret.secretKeyKey | quote }}
            {{- if .Values.authentik.bootstrap.enabled }}
            - name: AUTHENTIK_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "authentik.bootstrap.existingSecret is required" .Values.authentik.bootstrap.existingSecret | quote }}
                  key: {{ .Values.authentik.bootstrap.passwordKey | quote }}
            - name: AUTHENTIK_BOOTSTRAP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ required "authentik.bootstrap.existingSecret is required" .Values.authentik.bootstrap.existingSecret | quote }}
                  key: {{ .Values.authentik.bootstrap.emailKey | quote }}
            - name: AUTHENTIK_BOOTSTRAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ required "authentik.bootstrap.existingSecret is required" .Values.authentik.bootstrap.existingSecret | quote }}
                  key: {{ .Values.authentik.bootstrap.tokenKey | quote }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /-/health/live/
              port: 9000
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: 9000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: 9000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: media
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
