
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authentik.fullname" . }}-worker
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "authentik.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "authentik.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          args:
            - {{ .Values.worker.command | quote }}
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: {{ .Values.authentik.postgresql.host | quote }}
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: {{ .Values.authentik.postgresql.port | quote }}
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.authentik.postgresql.name | quote }}
            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.authentik.postgresql.user | quote }}
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.fullname" . }}-secret
                  key: AUTHENTIK_POSTGRESQL__PASSWORD
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.fullname" . }}-secret
                  key: AUTHENTIK_SECRET_KEY
            - name: AUTHENTIK_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.fullname" . }}-secret
                  key: AUTHENTIK_BOOTSTRAP_PASSWORD
            - name: AUTHENTIK_BOOTSTRAP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.fullname" . }}-secret
                  key: AUTHENTIK_BOOTSTRAP_EMAIL
            - name: AUTHENTIK_BOOTSTRAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.fullname" . }}-secret
                  key: AUTHENTIK_BOOTSTRAP_TOKEN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}